#!/bin/sh
#SBATCH --job-name="normal"
#SBATCH --ntasks=22
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=8
#SBATCH --time=01:00:00

set -ex
export OMP_NUM_THREADS=8
cd /users/sgodeck/PbSeSurface

aprun -n 22 -N 2 -d 8   ./bigdft
exit

