#!/bin/sh
#SBATCH --job-name="INTEL"
#SBATCH --ntasks=22
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:30:00
#SBATCH -C gpumodedefault

module switch PrgEnv-cray PrgEnv-intel
module load cudatoolkit

export OMP_NUM_THREADS=8

 date
 aprun  -n 22 -N 1 -d 8 -cc none  ./bigdft
 date

exit

