









#define FC_FUNC(name,NAME) name ## _


#define FC_FUNC_(name,NAME) name ## _


#define HAVE_CLOCK_GETTIME 1





#define HAVE_FC_FLUSH 1


#define HAVE_FC_GET_COMMAND_ARGUMENT 1











#define HAVE_LIBABINIT 1


#define HAVE_LIBRT 1





#define HAVE_LIBXC 1








#define HAVE_MPI2 1


#define HAVE_MPI3 1


#define HAVE_MPI_INIT_THREAD 1














#define HAVE_STRNDUP 1








#define HAVE_TIME_H 1





#define HAVE_YAML 


#define PACKAGE "bigdft"


#define PACKAGE_BUGREPORT "Damien.Caliste@cea.fr"


#define PACKAGE_NAME "BigDFT - DFT over wavelets"


#define PACKAGE_STRING "BigDFT - DFT over wavelets 1.7.6"


#define PACKAGE_TARNAME "bigdft"


#define PACKAGE_URL ""


#define PACKAGE_VERSION "1.7.6"





#define VERSION "1.7.6"
